userInput=input("Enter a string of letters: ")
a=userInput.count('a')
b=userInput.count('b')
c=userInput.count('c')
d=userInput.count('d')
e=userInput.count('e')
f=userInput.count('f')
g=userInput.count('g')
h=userInput.count('h')
i=userInput.count('i')
j=userInput.count('j')
k=userInput.count('k')
l=userInput.count('l')
m=userInput.count('m')
n=userInput.count('n')
o=userInput.count('o')
p=userInput.count('p')
q=userInput.count('q')
r=userInput.count('r')
s=userInput.count('s')
t=userInput.count('t')
u=userInput.count('u')
v=userInput.count('v')
w=userInput.count('w')
x=userInput.count('x')
y=userInput.count('y')
z=userInput.count('z')
list1=(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
list2=('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z')
print(list1)
for i in range(0,25):
    if (list1[i]>0):
        print(list2[i].upper(), end=" ")
        for j in range(list1[i]):
            print("*", end=" ")
        print(" ")
