def rot13(inputMessage=""):
    length=len(inputMessage)
    cipherText=""
    y=""
    for i in range(0, length):
        y=(inputMessage[i])
        if(ord(y)==97):
            cipherText=cipherText+"n"
        if(ord(y)==98):
            cipherText=cipherText+"o"
        if(ord(y)==99):
            cipherText=cipherText+"p"
        if(ord(y)==100):
            cipherText=cipherText+"q"
        if(ord(y)==101):
            cipherText=cipherText+"r"
        if(ord(y)==102):
            cipherText=cipherText+"s"
        if(ord(y)==103):
            cipherText=cipherText+"t"
        if(ord(y)==104):
            cipherText=cipherText+"u"
        if(ord(y)==105):
            cipherText=cipherText+"v"
        if(ord(y)==106):
            cipherText=cipherText+"w"
        if(ord(y)==107):
            cipherText=cipherText+"x"
        if(ord(y)==108):
            cipherText=cipherText+"y"
        if(ord(y)==109):
            cipherText=cipherText+"z"
        if(ord(y)==110):
            cipherText=cipherText+"a"
        if(ord(y)==111):
            cipherText=cipherText+"b"
        if(ord(y)==112):
            cipherText=cipherText+"c"
        if(ord(y)==113):
            cipherText=cipherText+"d"
        if(ord(y)==114):
            cipherText=cipherText+"e"
        if(ord(y)==115):
            cipherText=cipherText+"f"
        if(ord(y)==116):
            cipherText=cipherText+"g"
        if(ord(y)==117):
            cipherText=cipherText+"h"
        if(ord(y)==118):
            cipherText=cipherText+"i"
        if(ord(y)==119):
            cipherText=cipherText+"j"
        if(ord(y)==120):
            cipherText=cipherText+"k"
        if(ord(y)==121):
            cipherText=cipherText+"l"
        if(ord(y)==122):
            cipherText=cipherText+"m"
    print(inputMessage)
    print(cipherText)
rot13("hello")
